import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local"

const rubik = localFont({
  src: [
      {
        path: '/fonts/Rubik/rubik-v30-latin-regular.woff2',
        style: 'normal',
      },
  ],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${rubik.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
